CONFIG_ZMK_USB=n # ZMK_USB is only allowed when: not split or, split and role is central (i.e., not right_dongle)

## Size optimizations
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_ZMK_STUDIO=n

## PMW3610 Driver
## https://github.com/badjeff/zmk-pmw3610-driver
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610=y
CONFIG_ZMK_MOUSE=y
#CONFIG_SPI_LOG_LEVEL_DBG=y

## https://github.com/badjeff/zmk-pmw3610-driver/blob/main/src/pmw3610.c
CONFIG_PMW3610_SMART_ALGORITHM=y
# CONFIG_PMW3610_LOG_LEVEL_DBG=y

## Swap/Invert are now DTS properties in pixart,pmw3610 - see otello_pmw3610.dtsi
# CONFIG_PMW3610_INVERT_X=y // deprecated here, prefer DTS properties
# CONFIG_PMW3610_INVERT_Y=y // deprecated here, prefer DTS properties

CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=100
CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=200
CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=300
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=2000
CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=3000
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=30000
